- name: Ensure backup directory exists
  file:
    path: "{{ kasm_remote_backup_dir }}"
    state: directory
  become: true

- name: Backup database
  script: "files/backup.sh {{ kasm_remote_backup_dir }} {{ kasm_retention_days }}"
  register: backup_output
  become: true

# Pull the remote backup file from stdout of the backup script
- set_fact:
    remote_backup: "{{ backup_output.stdout_lines[-1:][0] }}"

- name: Copy database backup to ansible host
  fetch:
    src: "{{ remote_backup }}"
    dest: "{{ kasm_local_backup_dir }}"
    flat: true
  when:
    - kasm_local_backup_dir is defined
