# Setup default creds if users don't set them in the inventory

- set_fact:
    kasm_database_password: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=16') }}"
  when:
    - kasm_database_password | d('', true) | trim == ''
  run_once: true
  delegate_to: localhost

- set_fact:
    kasm_redis_password: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=16') }}"
  when:
    - kasm_redis_password | d('', true) | trim == ''
  run_once: true
  delegate_to: localhost
  
- set_fact:
    kasm_user_password: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=16') }}"
  when:
    - kasm_user_password | d('', true) | trim == ''
  run_once: true
  delegate_to: localhost

- set_fact:
    kasm_admin_password: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=16') }}"
  when:
    - kasm_admin_password | d('', true) | trim == ''
  run_once: true
  delegate_to: localhost

- set_fact:
    kasm_manager_token: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=16') }}"
  when:
    - kasm_manager_token | d('', true) | trim == ''
  run_once: true
  delegate_to: localhost

- set_fact:
    kasm_registration_token: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=22') }}"
  when:
    - kasm_registration_token | d('', true) | trim == ''
  run_once: true
  delegate_to: localhost
