- name: Check connection from web to postgres on db server
  wait_for:
    port: 5432
    host: "{{ db_ip }}"
    timeout: 60

- name: Check connection from web to redis on db server
  wait_for:
    port: 6379
    host: "{{ redis_ip }}"
    timeout: 60

- name: Init remote Database
  expect:
    timeout: 600
    command: >
      bash {{ tempdir.path }}/kasm_release/install.sh
        --role init_remote_db
        --accept-eula
        --proxy-port {{ kasm_proxy_port }}
        --db-hostname {{ kasm_database_hostname }}
        --db-password {{ kasm_database_password }}
        --database-user {{ kasm_database_user }}
        --database-name {{ kasm_database_name }}
        --db-master-user {{ kasm_database_master_user }}
        --db-master-password {{ kasm_database_master_password }}
        --db-port {{ kasm_database_port }}
        --server-zone {{ kasm_zone }}
        --manager-token {{ kasm_manager_token }}
        --registration-token {{ kasm_registration_token }}
        --redis-password {{ kasm_redis_password }}
        --user-password {{ kasm_user_password }}
        --admin-password {{ kasm_admin_password }}
        {{ '--no-db-ssl ' if not kasm_database_ssl }}
        {{ '--offline-service ' ~ service_images_copy.dest if service_images_file }}
    responses:
      Continue(?i): "y"
  run_once: true
  become: true

# XXX
- name: Turn off remote db init
  run_once: true
  delegate_to: localhost
  ansible.builtin.replace:
    dest: "{{ inventory_file }}"
    regexp: "init_remote_db: true"
    replace: "init_remote_db: false"
  when:
    - kasm_database_hostname

